# BUILD STAGE
FROM node:20-alpine AS builder

WORKDIR /app

COPY . .

# SERVE STAGE
FROM nginx:stable-alpine

COPY --from=builder /app /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]